---
Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      ImageId: ami-02f26adf094f51167
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  GithubActionTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      ImageId: ami-02f26adf094f51167
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref HTTPSecurityGroup

  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80 and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
